[tool.poetry]
name = "jetblack-markdown"
version = "0.4.0"
description = "A markdown extension for python documentation"
repository = "https://github.com/rob-blackbourn/jetblack-markdown"
authors = ["Rob Blackbourn <rob.blackbourn@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
  { include = "jetblack_markdown" }
]

[tool.poetry.dependencies]
python = "^3.7"
markdown = "^3.1"
docstring-parser = "^0.6"

[tool.poetry.dev-dependencies]
mypy = "^0.761.0"
autopep8 = "^1.4"
pytest = "^5.3"
mkdocs = "^1.0"
pylint = "^2.4"
mkdocs-material = "^4.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
